[package]
name = "PromptGen"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
clap = { version = "4.5", features = ["derive"] }
handlebars = "6.3.2"
serde = "1.0.219"
serde_derive = "1.0.219"
toml = "0.9.2"

[dev-dependencies]
assert_cmd = "2.0.17"
predicates = "3.1.3"
